### ISSUE TITLE
mount volume

### ISSUE THREAD

**Issue by uminomae** [42trans/ft_transcendence#9]
- topレベルでvolume定義を基本とする
```
volumes:
  postgres_vol:
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/postgres
      o: bind
 ```
serviceでは名前を使う
```
volumes:
  - pgadmin_vol:/var/lib/pgadmin
```
- 証明書や機密情報は直接マウントする
```
- ${SSL_CERT_PATH}:/etc/nginx/ssl/nginx.crt
```
